- id: input_tank
  alias: input_tank
  description: Input tank state notification
  trigger:
    - entity_id: binary_sensor.input_tank_high
      platform: state
      from: 'off'
      to: 'on'
      for:
        seconds: 2
    - entity_id: binary_sensor.input_tank_high
      platform: state
      from: 'on'
      to: 'off'
      for:
        seconds: 2
  action:
    - service: notify.astra_status
      data_template:
        message: >
          {% if is_state('binary_sensor.input_tank_high', 'on') %}
            'Notify: input tank HIGH'
          {% else %}
            'Notify: input tank OK'
          {% endif %}

- id: aerotank
  alias: aerotank
  description: Aerotank state notification
  trigger:
    - entity_id: binary_sensor.aerotank
      platform: state
      from: 'off'
      to: 'on'
      for:
        seconds: 2
    - entity_id: binary_sensor.aerotank
      platform: state
      from: 'on'
      to: 'off'
      for:
        seconds: 2
  action:
    - service: notify.astra_status
      data_template:
        message: >
          {% if is_state('binary_sensor.aerotank', 'on') %}
            'Notify: aerotank HIGH'
          {% else %}
            'Notify: aerotank OK'
          {% endif %}

- id: memory_card
  alias: memory_card
  description: Memory card space notification
  trigger:
    - entity_id: sensor.disk_use_percent
      platform: numeric_state
      above: 80
      for:
        minutes: 5
  action:
    - service: notify.astra_status
      data_template:
        message: "```memory card usage is high: {{ states.sensor.disk_use_percent.state }}\n```"

- id: telegram_astra_report
  alias: "Astra telegram report"
  description: "Astra status report"
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/status"
  condition: []
  action:
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: "```
input tank high: {{ states.binary_sensor.input_tank_high.state }}\n
input tank mid: {{ states.binary_sensor.input_tank_mid.state }}\n
input tank low: {{ states.binary_sensor.input_tank_low.state }}\n
aerotank: {{ states.binary_sensor.aerotank.state }}\n
temperature: {{ states.sensor.temperature.state }}\n
WiFi signal: {{ states.sensor.wifi_signal.state }}\n
```"

- id: telegram_hamster_report
  alias: "Hamster telegram report"
  description: "Hamster status report"
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/hub"
  condition: []
  action:
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: "```
memory usage: {{ states.sensor.memory_use_percent.state }}\n
card usage: {{ states.sensor.disk_use_percent.state }}\n
cpu usage: {{ states.sensor.processor_use.state }}\n
average 5min load: {{ states.sensor.load_5m.state }}\n
last boot: {{ states.sensor.last_boot.state }}\n
```"
