default_config:

lovelace:
  mode: yaml

mobile_app:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: astra_status
    platform: telegram
    chat_id: !secret telegram_chat_id

tts:
  - platform: google_translate

sensor:
  - platform: template
    sensors:
      astra_input_gauge:
        friendly_name: 'Astra gauge'
        unit_of_measurement: '%'
        value_template: >-
          {% if is_state('binary_sensor.input_tank_high', 'on') %}
            100
          {% elif is_state('binary_sensor.input_tank_mid', 'on') %}
            70
          {% elif is_state('binary_sensor.input_tank_low', 'on') %}
            40
          {% else %}
            10
          {% endif %}
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: disk_free
      - type: disk_use
      - type: memory_use_percent
      - type: processor_use
      - type: ipv4_address
      - type: last_boot
      - type: load_5m

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
